### ISSUE TITLE
LLM:Unable to refresh the conversation.

### ISSUE THREAD

**Issue by 2213500360** [sudomakes/backroad#12]
LLM: Unable to refresh the conversation.
When I tried to add a button to change the "messages" value to clear the conversation, I got a display bug, and the button and dialog were displayed incorrectly (two were displayed).
button related code:
`
let reset = br.button({ label: 'Reset', id: 'reset' });
if (reset) {
        chatHistory.messages = [];
        br.setValue('messages', [
            { by: 'ai', content: 'Hi, how can I help you today? ' },
        ]);
    }
`

![image](https://github.com/sudomakes/backroad/assets/67719519/25d058e3-8602-4cf1-aaba-ad0919742e42)

**Comment by sudo-vaibhav** [comment]
the issue seems to be some bug in the code re-rendering every node except the root one (which is why the issue seems to go away when I add another base node and start using that for the app). When you use the root node directly, the re-rendering logic seems to have something off. Will investigate further.

**Comment by 2213500360** [comment]
The issue was resolved after I added the re-rendering. I had tried to search for re-rendering related API in the documentation before, but couldn't find any. Thank you for your response.

**Comment by sudo-vaibhav** [comment]
should be fixed in @backroad/backroad@1.3.2 , lemme know if it doesn't work
